# Generated by Django 5.2.7 on 2025-11-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_sqft',
            field=models.FloatField(default=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='bhk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
