# Generated by Django 5.2.8 on 2025-11-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_images_alter_property_area_sqft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
